# Generated by rds-automation Lambda
# Request: {"database_name": "payments", "engine": "postgres", "environment": "dev"}

terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

provider "aws" {
  region = "us-east-1"
}

module "rds" {
  source = "../../modules/rds"

  db_name     = "payments"
  engine      = "postgres"
  environment = "dev"
  username    = "dbadmin"
  password    = var.password
}

variable "password" {
  description = "Master DB password"
  type        = string
  sensitive   = true
}

output "endpoint" {
  value = module.rds.endpoint
}
