import json
import logging
import os

import boto3
from github import Github

logger = logging.getLogger()
logger.setLevel(logging.INFO)

ALLOWED_ENGINES = ["postgres"]
ALLOWED_ENVIRONMENTS = ["dev", "prod"]

GITHUB_REPO = "jonathanjs66/RDSCluterAutomation"
GITHUB_BASE_BRANCH = "main"


def validate_request(body):
    required = ["database_name", "engine", "environment"]
    for field in required:
        if field not in body:
            raise ValueError(f"Missing required field: '{field}'")

    if body["engine"] not in ALLOWED_ENGINES:
        raise ValueError(f"Invalid engine '{body['engine']}'. Allowed: {ALLOWED_ENGINES}")

    if body["environment"] not in ALLOWED_ENVIRONMENTS:
        raise ValueError(f"Invalid environment '{body['environment']}'. Allowed: {ALLOWED_ENVIRONMENTS}")


def generate_terraform(database_name, engine, environment):
    return f"""# Generated by rds-automation Lambda
# Request: {{"database_name": "{database_name}", "engine": "{engine}", "environment": "{environment}"}}

terraform {{
  required_providers {{
    aws = {{
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }}
  }}
}}

provider "aws" {{
  region = "us-east-1"
}}

module "rds" {{
  source = "../../modules/rds"

  db_name     = "{database_name}"
  engine      = "{engine}"
  environment = "{environment}"
  username    = "dbadmin"
  password    = var.password
}}

variable "password" {{
  description = "Master DB password"
  type        = string
  sensitive   = true
}}

output "endpoint" {{
  value = module.rds.endpoint
}}
"""


def get_github_token():
    # Locally: set GITHUB_TOKEN env var
    # In Lambda: token lives in SSM (Chapter 7)
    token = os.environ.get("GITHUB_TOKEN")
    if token:
        return token

    ssm = boto3.client("ssm")
    response = ssm.get_parameter(
        Name="/rds-automation/github-token",
        WithDecryption=True,
    )
    return response["Parameter"]["Value"]


def create_github_pr(database_name, environment, tf_content):
    token = get_github_token()
    g = Github(token)
    repo = g.get_repo(GITHUB_REPO)

    branch_name = f"rds/{database_name}-{environment}"
    file_path = f"terraform/live/{database_name}-{environment}/main.tf"

    # Get the SHA of the base branch to branch off from
    base_sha = repo.get_branch(GITHUB_BASE_BRANCH).commit.sha

    # Create the new branch
    repo.create_git_ref(ref=f"refs/heads/{branch_name}", sha=base_sha)
    logger.info({"event": "branch_created", "branch": branch_name})

    # Commit the generated Terraform file
    repo.create_file(
        path=file_path,
        message=f"Add RDS config for {database_name} ({environment})",
        content=tf_content,
        branch=branch_name,
    )
    logger.info({"event": "file_committed", "path": file_path})

    # Open the PR
    pr = repo.create_pull(
        title=f"[RDS] Create {database_name} database ({environment})",
        body=(
            f"## New RDS Database Request\n\n"
            f"| Field | Value |\n"
            f"|---|---|\n"
            f"| Database name | `{database_name}` |\n"
            f"| Environment | `{environment}` |\n\n"
            f"Merging this PR will trigger CircleCI to run `terraform apply` "
            f"and create the RDS instance."
        ),
        head=branch_name,
        base=GITHUB_BASE_BRANCH,
    )
    logger.info({"event": "pr_opened", "url": pr.html_url})

    return pr.html_url


def lambda_handler(event, _context):
    logger.info("Received event: %s", json.dumps(event))

    record = event["Records"][0]
    body = json.loads(record["body"])

    validate_request(body)

    database_name = body["database_name"]
    engine = body["engine"]
    environment = body["environment"]

    tf_content = generate_terraform(database_name, engine, environment)

    pr_url = create_github_pr(database_name, environment, tf_content)

    logger.info({"event": "done", "pr_url": pr_url})

    return {
        "statusCode": 200,
        "database_name": database_name,
        "environment": environment,
        "pr_url": pr_url,
    }


if __name__ == "__main__":
    fake_sqs_event = {
        "Records": [
            {
                "body": json.dumps({
                    "database_name": "orders",
                    "engine": "postgres",
                    "environment": "dev"
                })
            }
        ]
    }

    result = lambda_handler(fake_sqs_event, None)
    print(f"\nPR opened: {result['pr_url']}")
